name: Build

on:
  pull_request:
    branches:
      - "main"

jobs:
  build-artifacts:
    if: ${{ !contains(github.event.head_commit.message, 'docs:') || github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # git status
      - name: Git status
        run: git status

      - name: Determine Branch
        id: branch
        uses: transferwise/sanitize-branch-name@v1

      # build
      - name: build artifacts
        id: build_artifacts
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.branch.outputs.sanitized-branch-name }}

      # artifacts
      - name: Push linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_linux
          path: dist/*linux*
