name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # git status
      - name: Git status
        run: git status

      # build
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
